export type Language = "en" | "ru";

const en = {
  skip: "Skip to content",
  location: "Your neighborhood European market · Plymouth, Minnesota",
  nav: ["Our shelves", "Our story", "Visit us"],
  menu: "Open menu",
  close: "Close menu",
  call: "Call the store",
  directions: "Get directions",
  eyebrow: "A familiar taste. A favorite place.",
  title: "A little taste\nof home.",
  intro: "German bread baked daily. An Eastern European deli, favorite groceries, and something sweet for the way home. Welcome to Arkady’s.",
  browse: "Explore our shelves",
  heroAlt: "An assortment of bread shown on Arkady’s Market’s Facebook page",
  heroCaption: "Good bread. Every day.",
  heroCaptionSmall: "German bread baked right here",
  proof: [
    { value: "30+", label: "years of familiar flavors" },
    { value: "Daily", label: "German bread baking" },
    { value: "Plymouth", label: "your neighborhood market" },
  ],
  shelvesEyebrow: "Come for a favorite. Find a new one.",
  shelvesTitle: "Everyday essentials,\nwith a European accent.",
  shelvesIntro: "From a loaf for tonight’s table to the treats you remember growing up, there’s plenty to explore.",
  shelves: [
    { title: "Bread & bakery", text: "Start with our German bread, baked daily. Pick up a loaf to share, or keep it all to yourself.", icon: "bread" },
    { title: "European deli", text: "Explore the deli counter for European meats, cheeses, and flavors to bring to your table.", icon: "deli" },
    { title: "Pantry & treats", text: "Discover imported groceries, candies, and drinks—from familiar favorites to something you haven’t tried.", icon: "pantry" },
  ],
  storyEyebrow: "A neighborhood tradition",
  storyTitle: "A world of flavors.\nRight around the corner.",
  storyText: "For more than 30 years, Arkady’s has been a place to reconnect with Eastern European food. Come for your everyday groceries, discover a new favorite, and take a little piece of home with you.",
  storyPoints: ["German bread baked daily", "An authentic Eastern European deli", "Imported groceries, sweets, and drinks"],
  storyAction: "See what’s new on Facebook",
  storyImageAlt: "Moldovan candies featured in a public Arkady’s Market post",
  storyImageCaption: "Something sweet from Moldova",
  storyImageSmall: "A glimpse of the treats on our shelves",
  drinksEyebrow: "Familiar favorites",
  drinksTitle: "For the table.\nFor the memories.",
  drinksText: "Find European drinks and pantry favorites to enjoy alongside fresh bread and your deli picks. Looking for something specific? Give us a call and ask what’s in store.",
  drinksImageAlt: "Kvass pictured on Arkady’s Market’s Facebook page",
  bandTitle: "Your next favorite is waiting.",
  bandText: "Stop by Arkady’s in Plymouth. We’d love to see you.",
  visitEyebrow: "Come say hello",
  visitTitle: "Make yourself\nat home.",
  visitText: "Find us on Highway 169 in Plymouth. Call ahead for product availability or questions about your visit.",
  addressLabel: "Find the store",
  hoursLabel: "Opening hours",
  hoursDays: "Monday–Sunday",
  hoursText: "10am–9pm",
  hoursNote: "Please call to confirm holiday hours.",
  contactLabel: "A question for us?",
  visitCardLabel: "Plymouth, Minnesota",
  visitCardTitle: "A local stop.\nA world of good food.",
  visitCardText: "3435 Highway 169 N",
  footer: "Eastern European deli & groceries. German bread baked daily.",
  facebook: "Facebook",
  copyright: "Arkady’s Market",
};

const ru: typeof en = {
  skip: "Перейти к содержимому",
  location: "Европейские продукты рядом с вами · Плимут, Миннесота",
  nav: ["Ассортимент", "О магазине", "Как нас найти"],
  menu: "Открыть меню",
  close: "Закрыть меню",
  call: "Позвонить",
  directions: "Построить маршрут",
  eyebrow: "Знакомый вкус. Любимое место.",
  title: "Вкус, который\nнапоминает дом.",
  intro: "Немецкий хлеб каждый день. Восточноевропейские деликатесы, любимые продукты и что-нибудь сладкое по дороге домой. Добро пожаловать в Arkady’s.",
  browse: "Наш ассортимент",
  heroAlt: "Ассортимент хлеба на странице Arkady’s Market в Facebook",
  heroCaption: "Свежий хлеб. Каждый день.",
  heroCaptionSmall: "Немецкий хлеб из нашей пекарни",
  proof: [
    { value: "30+", label: "лет знакомых вкусов" },
    { value: "Каждый день", label: "печём немецкий хлеб" },
    { value: "Плимут", label: "магазин рядом с вами" },
  ],
  shelvesEyebrow: "За любимым — и за новым",
  shelvesTitle: "Продукты на каждый день.\nСо вкусом Европы.",
  shelvesIntro: "Хлеб к сегодняшнему ужину, сладости из детства и новые вкусы — у нас есть что попробовать.",
  shelves: [
    { title: "Хлеб и выпечка", text: "Начните с немецкого хлеба, который мы печём каждый день. Возьмите буханку к семейному столу.", icon: "bread" },
    { title: "Европейские деликатесы", text: "Загляните к прилавку за европейскими колбасами, сырами и любимыми вкусами к вашему столу.", icon: "deli" },
    { title: "Продукты и сладости", text: "Привозные продукты, конфеты и напитки — от знакомых любимых марок до того, что ещё не пробовали.", icon: "pantry" },
  ],
  storyEyebrow: "Знакомое место по соседству",
  storyTitle: "Вкусы со всего мира.\nСовсем рядом.",
  storyText: "Уже более 30 лет Arkady’s знакомит соседей с восточноевропейскими продуктами. Приходите за покупками, находите новые любимые вкусы и уносите с собой частичку дома.",
  storyPoints: ["Немецкий хлеб каждый день", "Настоящие восточноевропейские деликатесы", "Привозные продукты, сладости и напитки"],
  storyAction: "Новости магазина в Facebook",
  storyImageAlt: "Молдавские конфеты из публикации Arkady’s Market",
  storyImageCaption: "Сладкий привет из Молдовы",
  storyImageSmall: "Немного вкусного с наших полок",
  drinksEyebrow: "Любимые вкусы",
  drinksTitle: "Для вашего стола.\nДля тёплых воспоминаний.",
  drinksText: "Выбирайте европейские напитки и любимые продукты к свежему хлебу и деликатесам. Ищете что-то определённое? Позвоните и уточните, что есть в наличии.",
  drinksImageAlt: "Квас на странице Arkady’s Market в Facebook",
  bandTitle: "Приходите за любимыми вкусами.",
  bandText: "Ждём вас в Arkady’s в Плимуте. Будем рады видеть!",
  visitEyebrow: "Загляните к нам",
  visitTitle: "Чувствуйте себя\nкак дома.",
  visitText: "Мы находимся на Highway 169 в Плимуте. Позвоните, чтобы уточнить наличие продуктов или задать вопрос.",
  addressLabel: "Адрес магазина",
  hoursLabel: "Часы работы",
  hoursDays: "Понедельник–воскресенье",
  hoursText: "10:00–21:00",
  hoursNote: "Часы работы в праздники уточняйте по телефону.",
  contactLabel: "Есть вопрос?",
  visitCardLabel: "Плимут, Миннесота",
  visitCardTitle: "Рядом с вами.\nСо вкусом всего мира.",
  visitCardText: "3435 Highway 169 N",
  footer: "Восточноевропейские продукты и деликатесы. Немецкий хлеб каждый день.",
  facebook: "Facebook",
  copyright: "Arkady’s Market",
};

export const content = { en, ru };
export type HomeContent = typeof en;
